# -*- coding: utf-8 -*-
"""Python - Error Handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UHeZx4nxu7iudTtsGlFmICp3KOQeVka_

## Exception | Try - Except
"""

student = {
    "name" : "Jhon",
    "address" : "Jakarta"
}
# print(stdnt)

print("code selanjutnya")

student = {
    "name" : "Jhon",
    "address" : "Jakarta"
}

try:
  print(stdnt)
except:
  print("An Error Occured")

print("code selanjutnya")

"""## Many Exception | Try - Except"""

student = {
    "name" : "Jhon",
    "address" : "Jakarta"
}

try:
  print(stdnt)
except NameError:
  print("Variable name is not defined")
except:
  print("An Error Occured")

print("code selanjutnya")

"""## Exception | Else"""

student = {
    "name" : "Jhon",
    "address" : "Jakarta"
}

try:
  print(student)
except NameError:
  print("Variable name is not defined")
except:
  print("An Error Occured")
else:
  print("Success")

print("code selanjutnya")

"""## Exception | Finally"""

student = {
    "name" : "Jhon",
    "address" : "Jakarta"
}

try:
  print(student)
except NameError:
  print("Variable name is not defined")
except:
  print("An Error Occured")
else:
  print("Success")
finally:
  print("Script has run!")

print("code selanjutnya")

"""## Exception | Raise"""

loop = int(input("Enter a number: "))
if loop <= 1:
  raise Exception("Number must be > 1")
else:
  for i in range(loop):
    print(i)

loop = int(input("Enter a number: "))
try:
  if loop <= 1:
    raise Exception("Number must be > 1")
  else:
    for i in range(loop):
      print(i)
except Exception as e:
  print(e)

"""## Simple Division"""

try:
  num1 = float(input("Enter the first number: "))
  num2 = float(input("Enter the second number: "))

  if num2 == 0:
    raise ZeroDivisionError("Error: Cannot divide by zero")

  result = num1/num2
  print("Result: ", result)
except ZeroDivisionError as e:
  print(e)
except ValueError:
  print("Error : Please enter valid number only")

