# -*- coding: utf-8 -*-
"""Python - Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ux-NivcLkSJyBMMxv8V0RS-4UZraXJBT

## Custom Function
"""

def greeting():
  print("Hello semuanya..")

greeting()
greeting()

"""## Function Arguments"""

def sayHello(name):
  print(f'Hello {name}')

sayHello('Fatih')
sayHello('Tuti')

"""## Return"""

def addition(a, b):
  add = a + b
  return add

hasil = addition(10,6)
print("Hasil penjumlahan ", hasil)

c = hasil + 8
print(c)

def addition(a, b):
  add = a + b
  print(add)

hasil = addition(10,6)
print("Hasil penjumlahan ", hasil)

def add(num1, num2):
  result = num1 + num2
  return f"{num1} + {num2} = {result}"

number = int(input("Enter a number to add : "))
loop = int(input("Enter how many loops : "))

for i in range(1,loop+1):
  print(add(number, i))

"""## Simple Calculator Function"""

def addition(num1, num2):
  return num1+num2

def sub(num1, num2):
  return num1-num2

def multiply(num1, num2):
  return num1*num2

def div(num1, num2):
  try:
    result = num1 / num2
    return result
  except ZeroDivisionError:
    return "Error: Cannot divide by zero"

try:
  angka1 = float(input("Enter the first number: "))
  angka2 = float(input("Enter the second number: "))

  print("Addition: ", addition(angka1, angka2))
  print("Substaction: ", sub(angka1, angka2))
  print("Multiplication: ", multiply(angka1, angka2))
  print("Division: ", div(angka1, angka2))

except Exception as e:
  print(e)
  print("Error: Please enter valid number only")

print('Hello')