# -*- coding: utf-8 -*-
"""Python - Local and Global Scope.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eHaZWRavRdRGhRi7ulZIqQKyfFLMlUHv

## Global Scope
"""

x = 10 # global variable

def test_global_scope():
  print(x)

test_global_scope()
print(x)

"""## Local Scope"""

def test_local_scope():
  n = 99
  print(n)

test_local_scope()
# print(n) # akan error karena n tidak terdefinisi

"""## Global and Local Scope Variable"""

x = 10 # global variable
score = 0

def test_global_scope():
  global x, score
  x += 1
  score += 2
  print(x)


test_global_scope()
print(x)
print(score)

"""## Overlapping Variable"""

a = 8 # variable global

def my_function():
  a = 23
  print("Nilai a di dalam fungsi: ", a)

my_function()
print("Nilai a di luar fungsi: ", a)

"""## Grocery Shopping List"""

items = ["Milk", "Bread", "Sugar", "Meat", "Cheese"]

cartList = [] # global variable

def buy(item):
    global cartList
    cartList.append(item)

print("Grocery List:")
for item in items:
    print("-", item)

while True:
    item = input("Enter an item to add to the grocery list (or type 'done' to finish): ")
    if item.lower() == 'done':
        break
    # Check if the item is in the items list
    if item in items:
        buy(item)
    else:
        print("Item not found in the grocery list. Please choose from the provided list.")
        continue

print("\nYour Cart:")
for item in cartList:
    print("-", item)