print("Registration Form")
print("-----------------")
name = input("Enter your name: ")
address = input("Enter your address: ")
email = input("Enter your email: ")

print("Thank you for registering!")
print("Name : ", name)
print("address : " + address)
print(f"Email : {email}")